### ISSUE TITLE
suggest to enable Zenodo integration and create periodic releases

### ISSUE THREAD

**Issue by jhpoelen** [plazi/treatments-rdf#1]
Thanks for putting Plazi rdf graphs in this repository. 

I want to suggest to enable Zenodo integration and create periodic releases, so that this valuable information is published through a second channel. If you've done this already, please include a readme with links to relevant data publications.

Thanks for all the hard work you do!

**Comment by jhpoelen** [comment]
related issue https://github.com/globalbioticinteractions/nomer/issues/23#issuecomment-700942468 .

**Comment by jhpoelen** [comment]
For the time being, I created the following Zenodo publication with an archived copy of Plazi Treatment RDFs - 

Plazi. (2020). Plazi Treatment RDF Archive (Version 0.1) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.4062537 .

**Comment by retog** [comment]
Hi @jhpoelen, I'm thinking if we could automate this process with travis. We could then upload the zip as GitHub release. Would this help?

**Comment by jhpoelen** [comment]
@retog Thanks for your message! 

I can already easily get to a generated zip file via GitHub. Also, note that by making a GitHub release, a zip archive is generated automatically, so there's no need for a custom travis workflow.

My original suggestion in this issue was to push a released copy of the Plazi graph to a non-GitHub location like Zenodo. Zenodo would then host this valuable information in a secondary, non-commercial, location. Also, Zenodo issues doi's for their publication, something that Github does not. I've been using the automated Zenodo-Github integration successfully for many years now, so maybe this would work for you also.

**Comment by retog** [comment]
Thanks @jhpoelen!

I've enabled the zenodo integrations and releases will now be available here: https://zenodo.org/account/settings/github/repository/plazi/treatments-rdf

We should discuss/decide how often we want to release.

**Comment by jhpoelen** [comment]
@retog Thanks! I was able to find the publication at Reto Gmür. (2020, October 21). plazi/treatments-rdf 20201002 (Version 20201002). Zenodo. http://doi.org/10.5281/zenodo.4115304 .
