### ISSUE TITLE
There is no additional information for taxon name Suillus praetermissus in the RDF representation. 

### ISSUE THREAD

**Issue by andrawaag** [plazi/treatments-rdf#12]
<http://taxon-name.plazi.org/id/Animalia/Suillus_praetermissus> in https://raw.githubusercontent.com/plazi/treatments-rdf/main/data/00/B0/41/00B04160E78A5AAC836788ABFF357770.ttl does not exist in that rdf

**Comment by nleanba** [comment]
This is fixed with the updated xml to rdf generator (https://github.com/plazi/gg2rdf)
