### ISSUE TITLE
Treatment 038987A6F307FF98EF5062955B36F1E5 refers to a DOI that does not resolve.

### ISSUE THREAD

**Issue by andrawaag** [plazi/treatments-rdf#14]
The treatment at https://raw.githubusercontent.com/plazi/treatments-rdf/main/data/03/89/87/038987A6F307FF98EF5062955B36F1E5.ttl  lists a non-existing or none-resolving DOI: 10.5252/geodiversitas2023v45a19

**Comment by nleanba** [comment]
http://dx.doi.org/10.5252/geodiversitas2023v45a19 does resolve (and redirect)

If you think this is the wrong url / id, please move this issue to plazi/treatments-xml, where the data is taken from.
