### ISSUE TITLE
https://raw.githubusercontent.com/plazi/treatments-rdf/main/data/03/89/87/038987A6F307FF98EF5062955B36F1E5.ttl cannot be added to Wikidata because the DOI does not resolve

### ISSUE THREAD

**Issue by andrawaag** [plazi/treatments-rdf#15]
The treament: https://raw.githubusercontent.com/plazi/treatments-rdf/main/data/03/89/87/038987A6F307FF98EF5062955B36F1E5.ttl can currently not be added to Wikidata. The DOI: 10.5252/geodiversitas2023v45a19 does not resolve.

**Comment by andrawaag** [comment]
Already stated in #14

**Comment by myrmoteras** [comment]
@andrawaag it seems that this is an issue of when he doi becomes available. What to do, once it is available, and thus resolve the issue?

**Comment by andrawaag** [comment]
@myrmoteras Once the DOI becomes available, we simply rerun the bot with the treatment UUID as input. We could also decide to simply add the DOI but this will lead to non-resolving links in Wikidata, which maybe something we don't want at this stage.
