### ISSUE TITLE
https://raw.githubusercontent.com/plazi/treatments-rdf/main/data/03/A3/87/03A387D3DA4F5F52FDBEFD71FB1BFB2E.ttl cannot be added to Wikidata because the DOI does not resolve

### ISSUE THREAD

**Issue by andrawaag** [plazi/treatments-rdf#16]
The treament: https://raw.githubusercontent.com/plazi/treatments-rdf/main/data/03/A3/87/03A387D3DA4F5F52FDBEFD71FB1BFB2E.ttl can currently not be added to Wikidata. The DOI: 10.1080/00222933.2023.2242099 does not resolve.

**Comment by nleanba** [comment]
http://dx.doi.org/10.1080/00222933.2023.2242099 does resolve (and redirect)

If you think this is the wrong url / id, please move this issue to plazi/treatments-xml, where the data is taken from
