### ISSUE TITLE
PSPS Deployment to triple store lagging

### ISSUE THREAD

**Issue by retog** [plazi/treatments-rdf#3]
https://github.com/plazi/treatments-rdf/blob/main/data/03/FE/87/03FE879EC9161676FE88FC3DFD79B7D9.ttl contains the triple

<http://treatment.plazi.org/id/03FE879EC9161676FE88FC3DFD79B7D9>  trt:deprecates <http://taxon-concept.plazi.org/id/Animalia/Leprota_Melichar1_1912>

this triple is not currently in the triple store.

@nleanba, I think we should replace PSPS with something more specific. A new service with a webhook or a github action that directly sends a SPARQL update, wdyt?

**Comment by retog** [comment]
PSPS also provides an authenticating proxy to the triple store.
Options:
- keep psps for that
- use triple store with auth
- include this in new tool
- use/write separate tool

**Comment by nleanba** [comment]
Webhook →
Check for changed files →
send appropriate update/upload statements →
  a) run specific postupdate (more comlexity for the SPSPSR)
  b) run same postupdate     (more load on triplestore)

**Comment by retog** [comment]
Updates now done efficiently by https://github.com/plazi/turtle-hook/
PSPS still in place as endpoint proxy.
